services:
  - type: web
    name: android-apk-license-packer
    env: docker
    plan: free
    autoDeploy: true
    envVars:
      - key: DEFAULT_LICENSE_SERVER
        value: https://android-license-gateway-phone.pages.dev
